### ISSUE TITLE
Unhandled Exception: HiveError: Cannot write, unknown type: _$Orange. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by mohammadne** [felangel/hydrated_bloc#55]
I am using ```hydrated_bloc``` with ```Freezed``` package.

**State is:**
```
@freezed
abstract class ThemeState with _$ThemeState {
  const factory ThemeState({
    @required ThemeScheme theme,
    @required ThemeBrightness brightness,
  }) = _ThemeState;

  factory ThemeState.fromJson(Map<String, dynamic> json) =>
      _$ThemeStateFromJson(json);
}
```
**ThemeScheme is:**
```
@freezed
abstract class ThemeScheme with _$ThemeScheme {
  const factory ThemeScheme.orange() = Orange;
  const factory ThemeScheme.blue() = Blue;

  factory ThemeScheme.fromJson(Map<String, dynamic> json) =>
      _$ThemeSchemeFromJson(json);
}
```
**ThemeBrightness  is:**
```
@freezed
abstract class ThemeBrightness with _$ThemeBrightness {
  const factory ThemeBrightness.light() = Light;
  const factory ThemeBrightness.dark() = Dark;

  factory ThemeBrightness.fromJson(Map<String, dynamic> json) =>
      _$ThemeBrightnessFromJson(json);
}
```

and:
```
@override
  ThemeState fromJson(Map<String, dynamic> json) {
    try {
      final state = ThemeState.fromJson(json);
      return state;
    } catch (_) {
      return null;
    }
  }

  @override
  Map<String, dynamic> toJson(ThemeState state) {
    return state.toJson();
  }
```

but I get :
```
E/flutter (22951): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: HiveError: Cannot write, unknown type: _$Orange. Did you forget to register an adapter?
E/flutter (22951): #0      BinaryWriterImpl.write 
package:hive/…/binary/binary_writer_impl.dart:310
E/flutter (22951): #1      BinaryWriterImpl.writeMap 
package:hive/…/binary/binary_writer_impl.dart:215
E/flutter (22951): #2      BinaryWriterImpl.write 
package:hive/…/binary/binary_writer_impl.dart:306
E/flutter (22951): #3      BinaryWriterImpl.writeFrame 
package:hive/…/binary/binary_writer_impl.dart:254
E/flutter (22951): #4      StorageBackendVm.writeFrames.<anonymous closure> 
package:hive/…/vm/storage_backend_vm.dart:123
E/flutter (22951): #5      ReadWriteSync.syncWrite.<anonymous closure> 
package:hive/…/vm/read_write_sync.dart:26
E/flutter (22951): #6      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (22951): #7      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (22951): #8      _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (22951): #9      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:686:45)
E/flutter (22951): #10     Future._propagateToListeners  (dart:async/future_impl.dart:715:32)
E/flutter (22951): #11     Future._addListener.<anonymous closure>  (dart:async/future_impl.dart:391:9)
E/flutter (22951): #12     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (22951): #13     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (22951): #14     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (22951): #15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (22951): #16     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (22951): #17     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
E/flutter (22951):
```

**Comment by mohammadne** [comment]
any suggestion ?

**Comment by tenhobi** [comment]
This is clearly an error on Hive side, as you can see 'cause it's a `HiveError`... :D 

Take a look at this https://github.com/hivedb/hive/issues/241 or something similar.

**Comment by mohammadne** [comment]
I don't know about hive.
what do I should do about it ?

**Comment by orsenkucher** [comment]
@mohammadne try to
```dart
const factory ThemeState({
    @required @JsonKey(toJson: _toS) ThemeScheme theme,
    @required @JsonKey(toJson: _toB) ThemeBrightness brightness,
  }) = _ThemeState;
```
and outside `ThemeScheme` class put
```dart
Map<String, dynamic> _toS(ThemeScheme s) => s?.toJson();
Map<String, dynamic> _toB(ThemeBrightness b) => b?.toJson();
```
hope this will help😛

**Comment by mohammadne** [comment]
> @mohammadne try to
> 
> ```dart
> const factory ThemeState({
>     @required @JsonKey(toJson: _toS) ThemeScheme theme,
>     @required @JsonKey(toJson: _toB) ThemeBrightness brightness,
>   }) = _ThemeState;
> ```
> 
> and outside `ThemeScheme` class put
> 
> ```dart
> Map<String, dynamic> _toS(ThemeScheme s) => s?.toJson();
> Map<String, dynamic> _toB(ThemeBrightness b) => b?.toJson();
> ```
> 
> hope this will help😛

Perfect , That was the answer.
